"use strict";
// this intermediary file is required in order to be able to generate TypeScript definitions
// all exports in this file must also be exported from ../app/index.js
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Prop = exports.PropsList = exports.StrechBar = exports.SlidingToolbar = exports.SubNavDivider = exports.SubNav = exports.LeftMenu = exports.TabList = exports.Tab = exports.NavButton = exports.CheckButtonGroup = exports.CheckGroup = exports.CheckboxButton = exports.RadioButtonGroup = exports.Checkbox = exports.RadioGroup = exports.Loader = exports.ButtonGroup = exports.SwitchGroup = exports.Switch = exports.FormLabel = exports.TimePickerV2 = exports.TimePicker = exports.DatePickerISO = exports.DateTimePicker = exports.DatePicker = exports.getDurationString = exports.DurationInput = exports.Tooltip = exports.IconLabel = exports.IconButton = exports.Rotate = exports.AvatarPlaceholder = exports.Avatar = exports.AvatarGroup = exports.AvatarContentImage = exports.AvatarContentText = exports.AvatarWrapper = exports.Alert = exports.Badge = exports.Card = exports.Label = exports.Popover = exports.WithPagination = exports.SelectWithTemplate = exports.Option = exports.Select = exports.Input = exports.Button = exports.HelloWorld = void 0;
exports.LoadingOverlay = exports.Spinner = exports.ListItemLoader = exports.Skeleton = exports.IllustrationButton = exports.SvgIconIllustration = exports.WithSizeObserver = exports.SearchBar = exports.CreateButton = exports.DropZone = exports.ThemeSelector = exports.IconPicker = exports.SelectGrid = exports.ToggleBox = exports.Menu = exports.toasted = exports.GridItemCheckWrapper = exports.GridItemTopActions = exports.GridItemFooterActions = exports.GridItemFooterBlock = exports.GridItemSlug = exports.GridItemText = exports.GridItemTitle = exports.GridItemTime = exports.GridItemContentBlock = exports.GridItemFooter = exports.GridItemMedia = exports.GridItemContent = exports.GridItem = exports.GridList = exports.Modal = exports.Carousel = exports.DonutChart = exports.Autocomplete = exports.EmptyState = exports.Tabs = exports.TabContent = exports.TabPanel = exports.TabLabel = exports.TagInput = exports.Tag = exports.Dropdown = exports.DropdownDivider = exports.DropdownLabel = exports.DropdownItem = exports.DropdownFirst = exports.HeadingText = exports.ContentDivider = exports.Divider = exports.Icon = void 0;
exports.setupLocalization = exports.getTextColor = exports.WeeklyCalendarGridItem = exports.WeeklyCalendarGrid = exports.CalendarWeekDayItem = exports.DragHandle = exports.DragHandleDots = exports.ResizeObserverComponent = exports.SpacerBlock = exports.Spacer = exports.showPopup = exports.PopupPositioner = exports.WithPopover = exports.ResizablePanels = exports.MultiSelect = exports.ContentListItem = exports.TableListItem = exports.TableList = exports.TreeMenu = exports.TreeSelect = exports.BottomNav = exports.Heading = exports.Time = exports.Text = void 0;
var HelloWorld_1 = require("./components/HelloWorld");
Object.defineProperty(exports, "HelloWorld", { enumerable: true, get: function () { return HelloWorld_1.HelloWorld; } });
var Button_1 = require("./components/Button");
Object.defineProperty(exports, "Button", { enumerable: true, get: function () { return Button_1.Button; } });
var Input_1 = require("./components/Input");
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return Input_1.Input; } });
var Select_1 = require("./components/Select");
Object.defineProperty(exports, "Select", { enumerable: true, get: function () { return Select_1.Select; } });
Object.defineProperty(exports, "Option", { enumerable: true, get: function () { return Select_1.Option; } });
var SelectWithTemplate_1 = require("./components/SelectWithTemplate");
Object.defineProperty(exports, "SelectWithTemplate", { enumerable: true, get: function () { return SelectWithTemplate_1.SelectWithTemplate; } });
var WithPagination_1 = require("./components/WithPagination");
Object.defineProperty(exports, "WithPagination", { enumerable: true, get: function () { return WithPagination_1.WithPagination; } });
var Popover_1 = require("./components/Popover");
Object.defineProperty(exports, "Popover", { enumerable: true, get: function () { return Popover_1.Popover; } });
var Label_1 = require("./components/Label");
Object.defineProperty(exports, "Label", { enumerable: true, get: function () { return Label_1.Label; } });
var Card_1 = require("./components/Card");
Object.defineProperty(exports, "Card", { enumerable: true, get: function () { return Card_1.Card; } });
var Badge_1 = require("./components/Badge");
Object.defineProperty(exports, "Badge", { enumerable: true, get: function () { return Badge_1.Badge; } });
var Alert_1 = require("./components/Alert");
Object.defineProperty(exports, "Alert", { enumerable: true, get: function () { return Alert_1.Alert; } });
var avatar_wrapper_1 = require("./components/avatar/avatar-wrapper");
Object.defineProperty(exports, "AvatarWrapper", { enumerable: true, get: function () { return avatar_wrapper_1.AvatarWrapper; } });
var avatar_text_1 = require("./components/avatar/avatar-text");
Object.defineProperty(exports, "AvatarContentText", { enumerable: true, get: function () { return avatar_text_1.AvatarContentText; } });
var avatar_image_1 = require("./components/avatar/avatar-image");
Object.defineProperty(exports, "AvatarContentImage", { enumerable: true, get: function () { return avatar_image_1.AvatarContentImage; } });
var avatar_group_1 = require("./components/avatar/avatar-group");
Object.defineProperty(exports, "AvatarGroup", { enumerable: true, get: function () { return avatar_group_1.AvatarGroup; } });
var avatar_1 = require("./components/avatar/avatar");
Object.defineProperty(exports, "Avatar", { enumerable: true, get: function () { return avatar_1.Avatar; } });
var avatar_placeholder_1 = require("./components/avatar/avatar-placeholder");
Object.defineProperty(exports, "AvatarPlaceholder", { enumerable: true, get: function () { return avatar_placeholder_1.AvatarPlaceholder; } });
var Rotate_1 = require("./components/Rotate");
Object.defineProperty(exports, "Rotate", { enumerable: true, get: function () { return Rotate_1.Rotate; } });
var IconButton_1 = require("./components/IconButton");
Object.defineProperty(exports, "IconButton", { enumerable: true, get: function () { return IconButton_1.IconButton; } });
var IconLabel_1 = require("./components/IconLabel");
Object.defineProperty(exports, "IconLabel", { enumerable: true, get: function () { return IconLabel_1.IconLabel; } });
var Tooltip_1 = require("./components/Tooltip");
Object.defineProperty(exports, "Tooltip", { enumerable: true, get: function () { return Tooltip_1.Tooltip; } });
var DurationInput_1 = require("./components/DurationInput");
Object.defineProperty(exports, "DurationInput", { enumerable: true, get: function () { return DurationInput_1.DurationInput; } });
var DurationInput_2 = require("./components/DurationInput");
Object.defineProperty(exports, "getDurationString", { enumerable: true, get: function () { return DurationInput_2.getDurationString; } });
var DatePicker_1 = require("./components/DatePicker");
Object.defineProperty(exports, "DatePicker", { enumerable: true, get: function () { return DatePicker_1.DatePicker; } });
var DateTimePicker_1 = require("./components/DateTimePicker");
Object.defineProperty(exports, "DateTimePicker", { enumerable: true, get: function () { return DateTimePicker_1.DateTimePicker; } });
var DatePicker_2 = require("./components/DatePicker");
Object.defineProperty(exports, "DatePickerISO", { enumerable: true, get: function () { return DatePicker_2.DatePickerISO; } });
var TimePicker_1 = require("./components/TimePicker");
Object.defineProperty(exports, "TimePicker", { enumerable: true, get: function () { return TimePicker_1.TimePicker; } });
var TimePickerV2_1 = require("./components/TimePickerV2");
Object.defineProperty(exports, "TimePickerV2", { enumerable: true, get: function () { return TimePickerV2_1.TimePickerV2; } });
var FormLabel_1 = require("./components/FormLabel");
Object.defineProperty(exports, "FormLabel", { enumerable: true, get: function () { return FormLabel_1.FormLabel; } });
var Switch_1 = require("./components/Switch");
Object.defineProperty(exports, "Switch", { enumerable: true, get: function () { return Switch_1.Switch; } });
var SwitchGroup_1 = require("./components/SwitchGroup");
Object.defineProperty(exports, "SwitchGroup", { enumerable: true, get: function () { return SwitchGroup_1.SwitchGroup; } });
var ButtonGroup_1 = require("./components/ButtonGroup");
Object.defineProperty(exports, "ButtonGroup", { enumerable: true, get: function () { return ButtonGroup_1.ButtonGroup; } });
var Loader_1 = require("./components/Loader");
Object.defineProperty(exports, "Loader", { enumerable: true, get: function () { return Loader_1.Loader; } });
var RadioGroup_1 = require("./components/RadioGroup");
Object.defineProperty(exports, "RadioGroup", { enumerable: true, get: function () { return RadioGroup_1.RadioGroup; } });
var Checkbox_1 = require("./components/Checkbox");
Object.defineProperty(exports, "Checkbox", { enumerable: true, get: function () { return Checkbox_1.Checkbox; } });
var RadioButtonGroup_1 = require("./components/RadioButtonGroup");
Object.defineProperty(exports, "RadioButtonGroup", { enumerable: true, get: function () { return RadioButtonGroup_1.RadioButtonGroup; } });
var CheckboxButton_1 = require("./components/CheckboxButton");
Object.defineProperty(exports, "CheckboxButton", { enumerable: true, get: function () { return CheckboxButton_1.CheckboxButton; } });
var CheckGroup_1 = require("./components/CheckGroup");
Object.defineProperty(exports, "CheckGroup", { enumerable: true, get: function () { return CheckGroup_1.CheckGroup; } });
var CheckButtonGroup_1 = require("./components/CheckButtonGroup");
Object.defineProperty(exports, "CheckButtonGroup", { enumerable: true, get: function () { return CheckButtonGroup_1.CheckButtonGroup; } });
var NavButton_1 = require("./components/NavButton");
Object.defineProperty(exports, "NavButton", { enumerable: true, get: function () { return NavButton_1.NavButton; } });
var TabList_1 = require("./components/TabList");
Object.defineProperty(exports, "Tab", { enumerable: true, get: function () { return TabList_1.Tab; } });
Object.defineProperty(exports, "TabList", { enumerable: true, get: function () { return TabList_1.TabList; } });
var LeftMenu_1 = require("./components/LeftMenu");
Object.defineProperty(exports, "LeftMenu", { enumerable: true, get: function () { return LeftMenu_1.LeftMenu; } });
var SubNav_1 = require("./components/SubNav");
Object.defineProperty(exports, "SubNav", { enumerable: true, get: function () { return SubNav_1.SubNav; } });
Object.defineProperty(exports, "SubNavDivider", { enumerable: true, get: function () { return SubNav_1.SubNavDivider; } });
var SlidingToolbar_1 = require("./components/SlidingToolbar");
Object.defineProperty(exports, "SlidingToolbar", { enumerable: true, get: function () { return SlidingToolbar_1.SlidingToolbar; } });
var StrechBar_1 = require("./components/StrechBar");
Object.defineProperty(exports, "StrechBar", { enumerable: true, get: function () { return StrechBar_1.StrechBar; } });
var PropsList_1 = require("./components/PropsList");
Object.defineProperty(exports, "PropsList", { enumerable: true, get: function () { return PropsList_1.PropsList; } });
Object.defineProperty(exports, "Prop", { enumerable: true, get: function () { return PropsList_1.Prop; } });
var Icon_1 = require("./components/Icon");
Object.defineProperty(exports, "Icon", { enumerable: true, get: function () { return Icon_1.Icon; } });
var Divider_1 = require("./components/Divider");
Object.defineProperty(exports, "Divider", { enumerable: true, get: function () { return Divider_1.Divider; } });
var ContentDivider_1 = require("./components/ContentDivider");
Object.defineProperty(exports, "ContentDivider", { enumerable: true, get: function () { return ContentDivider_1.ContentDivider; } });
var HeadingText_1 = require("./components/HeadingText");
Object.defineProperty(exports, "HeadingText", { enumerable: true, get: function () { return HeadingText_1.HeadingText; } });
var DropdownFirst_1 = require("./components/DropdownFirst");
Object.defineProperty(exports, "DropdownFirst", { enumerable: true, get: function () { return DropdownFirst_1.DropdownFirst; } });
var DropdownFirst_2 = require("./components/DropdownFirst");
Object.defineProperty(exports, "DropdownItem", { enumerable: true, get: function () { return DropdownFirst_2.DropdownItem; } });
var DropdownFirst_3 = require("./components/DropdownFirst");
Object.defineProperty(exports, "DropdownLabel", { enumerable: true, get: function () { return DropdownFirst_3.DropdownLabel; } });
var DropdownFirst_4 = require("./components/DropdownFirst");
Object.defineProperty(exports, "DropdownDivider", { enumerable: true, get: function () { return DropdownFirst_4.DropdownDivider; } });
var Dropdown_1 = require("./components/Dropdown");
Object.defineProperty(exports, "Dropdown", { enumerable: true, get: function () { return Dropdown_1.Dropdown; } });
var Tag_1 = require("./components/Tag");
Object.defineProperty(exports, "Tag", { enumerable: true, get: function () { return Tag_1.Tag; } });
var TagInput_1 = require("./components/TagInput");
Object.defineProperty(exports, "TagInput", { enumerable: true, get: function () { return TagInput_1.TagInput; } });
var TabCustom_1 = require("./components/TabCustom");
Object.defineProperty(exports, "TabLabel", { enumerable: true, get: function () { return TabCustom_1.TabLabel; } });
Object.defineProperty(exports, "TabPanel", { enumerable: true, get: function () { return TabCustom_1.TabPanel; } });
Object.defineProperty(exports, "TabContent", { enumerable: true, get: function () { return TabCustom_1.TabContent; } });
Object.defineProperty(exports, "Tabs", { enumerable: true, get: function () { return TabCustom_1.Tabs; } });
var EmptyState_1 = require("./components/EmptyState");
Object.defineProperty(exports, "EmptyState", { enumerable: true, get: function () { return EmptyState_1.EmptyState; } });
var Autocomplete_1 = require("./components/Autocomplete");
Object.defineProperty(exports, "Autocomplete", { enumerable: true, get: function () { return Autocomplete_1.Autocomplete; } });
var DonutChart_1 = require("./components/DonutChart");
Object.defineProperty(exports, "DonutChart", { enumerable: true, get: function () { return DonutChart_1.DonutChart; } });
var Carousel_1 = require("./components/Carousel");
Object.defineProperty(exports, "Carousel", { enumerable: true, get: function () { return Carousel_1.Carousel; } });
var Modal_1 = require("./components/Modal");
Object.defineProperty(exports, "Modal", { enumerable: true, get: function () { return Modal_1.Modal; } });
var GridList_1 = require("./components/GridList");
Object.defineProperty(exports, "GridList", { enumerable: true, get: function () { return GridList_1.GridList; } });
var GridItem_1 = require("./components/GridItem");
Object.defineProperty(exports, "GridItem", { enumerable: true, get: function () { return GridItem_1.GridItem; } });
Object.defineProperty(exports, "GridItemContent", { enumerable: true, get: function () { return GridItem_1.GridItemContent; } });
Object.defineProperty(exports, "GridItemMedia", { enumerable: true, get: function () { return GridItem_1.GridItemMedia; } });
Object.defineProperty(exports, "GridItemFooter", { enumerable: true, get: function () { return GridItem_1.GridItemFooter; } });
Object.defineProperty(exports, "GridItemContentBlock", { enumerable: true, get: function () { return GridItem_1.GridItemContentBlock; } });
Object.defineProperty(exports, "GridItemTime", { enumerable: true, get: function () { return GridItem_1.GridItemTime; } });
Object.defineProperty(exports, "GridItemTitle", { enumerable: true, get: function () { return GridItem_1.GridItemTitle; } });
Object.defineProperty(exports, "GridItemText", { enumerable: true, get: function () { return GridItem_1.GridItemText; } });
Object.defineProperty(exports, "GridItemSlug", { enumerable: true, get: function () { return GridItem_1.GridItemSlug; } });
Object.defineProperty(exports, "GridItemFooterBlock", { enumerable: true, get: function () { return GridItem_1.GridItemFooterBlock; } });
Object.defineProperty(exports, "GridItemFooterActions", { enumerable: true, get: function () { return GridItem_1.GridItemFooterActions; } });
Object.defineProperty(exports, "GridItemTopActions", { enumerable: true, get: function () { return GridItem_1.GridItemTopActions; } });
Object.defineProperty(exports, "GridItemCheckWrapper", { enumerable: true, get: function () { return GridItem_1.GridItemCheckWrapper; } });
var Toast_1 = require("./components/Toast");
Object.defineProperty(exports, "toasted", { enumerable: true, get: function () { return Toast_1.toasted; } });
var Menu_1 = require("./components/Menu");
Object.defineProperty(exports, "Menu", { enumerable: true, get: function () { return Menu_1.Menu; } });
var index_1 = require("./components/ToggleBox/index");
Object.defineProperty(exports, "ToggleBox", { enumerable: true, get: function () { return index_1.ToggleBox; } });
var SelectGrid_1 = require("./components/SelectGrid");
Object.defineProperty(exports, "SelectGrid", { enumerable: true, get: function () { return SelectGrid_1.SelectGrid; } });
var IconPicker_1 = require("./components/IconPicker");
Object.defineProperty(exports, "IconPicker", { enumerable: true, get: function () { return IconPicker_1.IconPicker; } });
var ThemeSelector_1 = require("./components/ThemeSelector");
Object.defineProperty(exports, "ThemeSelector", { enumerable: true, get: function () { return ThemeSelector_1.ThemeSelector; } });
var DropZone_1 = require("./components/DropZone");
Object.defineProperty(exports, "DropZone", { enumerable: true, get: function () { return DropZone_1.DropZone; } });
var CreateButton_1 = require("./components/CreateButton");
Object.defineProperty(exports, "CreateButton", { enumerable: true, get: function () { return CreateButton_1.CreateButton; } });
var SearchBar_1 = require("./components/SearchBar");
Object.defineProperty(exports, "SearchBar", { enumerable: true, get: function () { return SearchBar_1.SearchBar; } });
var WithSizeObserver_1 = require("./components/WithSizeObserver");
Object.defineProperty(exports, "WithSizeObserver", { enumerable: true, get: function () { return WithSizeObserver_1.WithSizeObserver; } });
var SvgIconIllustration_1 = require("./components/SvgIconIllustration");
Object.defineProperty(exports, "SvgIconIllustration", { enumerable: true, get: function () { return SvgIconIllustration_1.SvgIconIllustration; } });
var IllustrationButton_1 = require("./components/IllustrationButton");
Object.defineProperty(exports, "IllustrationButton", { enumerable: true, get: function () { return IllustrationButton_1.IllustrationButton; } });
__exportStar(require("./components/Layouts"), exports);
__exportStar(require("./components/Form"), exports);
__exportStar(require("./components/Navigation"), exports);
__exportStar(require("./components/Lists"), exports);
var Skeleton_1 = require("./components/Skeleton");
Object.defineProperty(exports, "Skeleton", { enumerable: true, get: function () { return Skeleton_1.Skeleton; } });
var ListItemLoader_1 = require("./components/ListItemLoader");
Object.defineProperty(exports, "ListItemLoader", { enumerable: true, get: function () { return ListItemLoader_1.ListItemLoader; } });
var Spinner_1 = require("./components/Spinner");
Object.defineProperty(exports, "Spinner", { enumerable: true, get: function () { return Spinner_1.Spinner; } });
Object.defineProperty(exports, "LoadingOverlay", { enumerable: true, get: function () { return Spinner_1.LoadingOverlay; } });
var Text_1 = require("./components/Text/Text");
Object.defineProperty(exports, "Text", { enumerable: true, get: function () { return Text_1.Text; } });
var Time_1 = require("./components/Text/Time");
Object.defineProperty(exports, "Time", { enumerable: true, get: function () { return Time_1.Time; } });
var Heading_1 = require("./components/Text/Heading");
Object.defineProperty(exports, "Heading", { enumerable: true, get: function () { return Heading_1.Heading; } });
var BottomNav_1 = require("./components/Navigation/BottomNav");
Object.defineProperty(exports, "BottomNav", { enumerable: true, get: function () { return BottomNav_1.BottomNav; } });
var TreeSelect_1 = require("./components/TreeSelect/TreeSelect");
Object.defineProperty(exports, "TreeSelect", { enumerable: true, get: function () { return TreeSelect_1.TreeSelect; } });
var TreeMenu_1 = require("./components/TreeMenu");
Object.defineProperty(exports, "TreeMenu", { enumerable: true, get: function () { return TreeMenu_1.TreeMenu; } });
var TableList_1 = require("./components/Lists/TableList");
Object.defineProperty(exports, "TableList", { enumerable: true, get: function () { return TableList_1.TableList; } });
Object.defineProperty(exports, "TableListItem", { enumerable: true, get: function () { return TableList_1.TableListItem; } });
var ContentList_1 = require("./components/Lists/ContentList");
Object.defineProperty(exports, "ContentListItem", { enumerable: true, get: function () { return ContentList_1.ContentListItem; } });
var MultiSelect_1 = require("./components/MultiSelect");
Object.defineProperty(exports, "MultiSelect", { enumerable: true, get: function () { return MultiSelect_1.MultiSelect; } });
var ResizablePanels_1 = require("./components/ResizablePanels");
Object.defineProperty(exports, "ResizablePanels", { enumerable: true, get: function () { return ResizablePanels_1.ResizablePanels; } });
var WithPopover_1 = require("./components/WithPopover");
Object.defineProperty(exports, "WithPopover", { enumerable: true, get: function () { return WithPopover_1.WithPopover; } });
var ShowPopup_1 = require("./components/ShowPopup");
Object.defineProperty(exports, "PopupPositioner", { enumerable: true, get: function () { return ShowPopup_1.PopupPositioner; } });
Object.defineProperty(exports, "showPopup", { enumerable: true, get: function () { return ShowPopup_1.showPopup; } });
var common_1 = require("@sourcefabric/common");
Object.defineProperty(exports, "Spacer", { enumerable: true, get: function () { return common_1.Spacer; } });
Object.defineProperty(exports, "SpacerBlock", { enumerable: true, get: function () { return common_1.SpacerBlock; } });
var ResizeObserverComponent_1 = require("./components/ResizeObserverComponent");
Object.defineProperty(exports, "ResizeObserverComponent", { enumerable: true, get: function () { return ResizeObserverComponent_1.ResizeObserverComponent; } });
var DragHandleDots_1 = require("./components/DragHandleDots");
Object.defineProperty(exports, "DragHandleDots", { enumerable: true, get: function () { return DragHandleDots_1.DragHandleDots; } });
var DragHandle_1 = require("./components/DragHandle");
Object.defineProperty(exports, "DragHandle", { enumerable: true, get: function () { return DragHandle_1.DragHandle; } });
var CalendarWeekDayItem_1 = require("./components/Lists/CalendarWeekDayItem");
Object.defineProperty(exports, "CalendarWeekDayItem", { enumerable: true, get: function () { return CalendarWeekDayItem_1.CalendarWeekDayItem; } });
Object.defineProperty(exports, "WeeklyCalendarGrid", { enumerable: true, get: function () { return CalendarWeekDayItem_1.WeeklyCalendarGrid; } });
Object.defineProperty(exports, "WeeklyCalendarGridItem", { enumerable: true, get: function () { return CalendarWeekDayItem_1.WeeklyCalendarGridItem; } });
var helpers_1 = require("./helpers");
Object.defineProperty(exports, "getTextColor", { enumerable: true, get: function () { return helpers_1.getTextColor; } });
var localization_1 = require("./localization");
Object.defineProperty(exports, "setupLocalization", { enumerable: true, get: function () { return localization_1.setupLocalization; } });
